In [62]:
import pandas as pd

In [63]:
d={
 'Name': ['Ali', 'Ali','Bilal', 'Bilal', 'Ahmed', 'Ahmed'],
 'Subject': ['Math', 'Science', 'Math', 'Science', 'Math', 'Science'],
 'Marks': [85,90, 78, 82, 92, 88]
}

In [64]:
df=pd.DataFrame(d)

In [65]:
df

    Name  Subject  Marks
0    Ali     Math     85
1    Ali  Science     90
2  Bilal     Math     78
3  Bilal  Science     82
4  Ahmed     Math     92
5  Ahmed  Science     88

In [66]:
pt=pd.pivot_table(df, values='Marks',index='Name', columns='Subject', aggfunc='mean'
)

In [67]:
pt

Subject  Math  Science
Name
Ahmed    92.0     88.0
Ali      85.0     90.0
Bilal    78.0     82.0

In [68]:

d = {
    'Name': ['Ali','Ali','Ali','Ali',
             'Bilal','Bilal','Bilal','Bilal',
             'Ahmed','Ahmed','Ahmed','Ahmed'],

    'Subject': ['Math','Science','Math','Science',
                'Math','Science','Math','Science',
                'Math','Science','Math','Science'],

    'Marks': [85,90,88,92,
              78,82,80,85,
              92,88,95,90]
}

df = pd.DataFrame(d)
print(df)

     Name  Subject  Marks
0     Ali     Math     85
1     Ali  Science     90
2     Ali     Math     88
3     Ali  Science     92
4   Bilal     Math     78
5   Bilal  Science     82
6   Bilal     Math     80
7   Bilal  Science     85
8   Ahmed     Math     92
9   Ahmed  Science     88
10  Ahmed     Math     95
11  Ahmed  Science     90

In [69]:
pt=pd.pivot_table(df, values='Marks',index='Name', columns='Subject', aggfunc='sum')

In [70]:
pt

Subject  Math  Science
Name
Ahmed     187      178
Ali       173      182
Bilal     158      167

In [71]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/student_data_clean.csv')
df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
0,1001,Student_0,24,Other,Math,3,NaN,61.0,False,2021-09-11,26,33,Multan,10,NaN
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [81]:
df = df.dropna()
df

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
6,1007,Student_6,22,Female,Math,3,2.06,68.0,False,2022-05-02,8,23,Islamabad,2,Full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1025,1026,Student_25,18,Other,Math,8,2.01,89.0,False,2022-05-23,3,17,Multan,9,Installment
1026,1027,Student_26,21,Other,BBA,6,3.87,57.0,False,2021-02-12,15,13,Karachi,8,Full
1027,1028,Student_27,19,Female,Math,1,3.64,89.0,False,2020-10-26,7,17,Islamabad,8,Installment
1028,1029,Student_28,23,Male,EE,5,3.62,93.0,True,2022-06-26,15,27,Islamabad,5,Pending
1029,1030,Student_29,22,Other,Math,2,3.77,72.0,False,2021-08-24,26,23,Islamabad,9,Full

In [82]:
df.duplicated()

1       False
2       False
3       False
4       False
6       False
        ...
1025     True
1026     True
1027     True
1028     True
1029     True
Length: 931, dtype: bool

In [83]:
df.drop_duplicates()

,Student_ID,Name,Age,Gender,Department,Semester,CGPA,Attendance_Rate,Scholarship,Admission_Date,Midterm_Marks,Final_Marks,City,Study_Hours_Per_Day,Fees_Paid
1,1002,Student_1,21,Female,EE,1,3.94,98.0,False,2020-01-26,0,39,Lahore,5,Installment
2,1003,Student_2,22,Other,EE,5,2.44,66.0,False,2022-08-14,20,46,Faisalabad,7,Full
3,1004,Student_3,24,Male,EE,4,3.47,91.0,False,2021-02-24,19,14,Faisalabad,8,Full
4,1005,Student_4,20,Male,CS,2,3.53,79.0,False,2021-10-24,12,10,Karachi,3,Installment
6,1007,Student_6,22,Female,Math,3,2.06,68.0,False,2022-05-02,8,23,Islamabad,2,Full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,Student_995,23,Male,Math,3,3.88,81.0,False,2021-01-02,23,10,Islamabad,5,Full
996,1997,Student_996,18,Other,EE,7,3.55,89.0,False,2020-07-30,4,19,Multan,4,Installment
997,1998,Student_997,24,Female,Math,6,2.26,62.0,True,2021-07-30,23,47,Islamabad,8,Pending
998,1999,Student_998,21,Other,BBA,3,2.70,69.0,False,2022-08-18,23,8,Karachi,7,Installment
999,2000,Student_999,23,Female,BBA,3,2.87,84.0,False,2020-07-27,5,1,Lahore,6,Pending

In [72]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'Department', 'Semester', 'CGPA',
       'Attendance_Rate', 'Scholarship', 'Admission_Date', 'Midterm_Marks',
       'Final_Marks', 'City', 'Study_Hours_Per_Day', 'Fees_Paid'],
      dtype='object')

In [ ]:
pt = pd.pivot_table()

In [79]:
pt=pd.pivot_table(df, values=['Final_Marks','Midterm_Marks'],index='Department', columns='City')
pt

           Final_Marks                                              \
City        Faisalabad  Islamabad    Karachi     Lahore     Multan
Department
BBA          25.925000  25.441860  25.775000  24.840909  22.700000
CS           27.736842  28.147059  25.547619  23.857143  26.928571
EE           27.289474  25.848485  21.918919  24.581395  22.333333
Math         24.400000  28.150943  24.413043  26.104167  25.750000
Physics      20.352941  22.911765  22.720930  22.153846  25.361111

           Midterm_Marks
City          Faisalabad  Islamabad    Karachi     Lahore     Multan
Department
BBA            12.250000  15.534884  16.350000  13.681818  15.850000
CS             14.184211  16.058824  15.095238  13.857143  13.952381
EE             14.894737  17.939394  14.297297  13.767442  11.814815
Math           14.000000  15.867925  15.304348  13.541667  15.958333
Physics        14.264706  15.970588  16.465116  14.507692  15.500000

In [ ]:
import pandas as pd
df = pd.read_csv('C:/Users/BEST LAPTOP/Desktop/AI/student_data_clean.csv')
pt = pd.pivot_table(df,values='CGPA',index=['Department','Gender'], columns='Semester', aggfunc='mean')
pt

Semester                  1         2         3         4         5         6  \
Department Gender
BBA        Female  2.811250  2.545000  3.020833  2.955000  3.213333  3.380000
           Male    2.996000  2.965000  3.176667  3.030000  2.832857  2.853333
           Other   2.978571  3.078571  3.215455  2.900000  2.669000  2.843750
CS         Female  3.068000  2.747500  3.107500  2.952500  3.045000  3.246250
           Male    3.120000  3.385000  3.187778  3.357273  2.789167  3.153333
           Other   3.378750  2.998000  2.867500  3.597000  2.992500  2.774545
EE         Female  3.063750  3.540000  3.295000  2.810000  3.111250  3.228333
           Male    2.925714  3.070000  2.627500  3.186923  3.150000  3.290000
           Other   3.114286  2.448000  3.324000  2.926000  3.044286  3.301429
Math       Female  3.287000  3.131111  2.806667  2.985556  3.015000  2.995714
           Male    3.206000  2.790000  3.158000  3.250714  3.047500  2.960000
           Other   3.050000  2.932222  2.958182  3.088750  2.807273  3.070000
Physics    Female  3.194286  2.802222  2.974615  2.878333  3.044000  3.004444
           Male    2.903750  3.176364  2.794545  3.015556  2.926000  3.420000
           Other   2.966667  3.081000  3.187273  2.992500  2.790000  3.003333

Semester                  7         8
Department Gender
BBA        Female  3.358750  2.981429
           Male    3.213000  3.055385
           Other   3.076000  3.492500
CS         Female  2.924444  2.636000
           Male    3.112500  3.238571
           Other   2.987500  2.867143
EE         Female  2.980000  3.097000
           Male    3.028182  2.882222
           Other   2.835000  2.893750
Math       Female  3.108000  2.741111
           Male    3.255000  3.606667
           Other   3.108182  2.924615
Physics    Female  2.898571  3.440000
           Male    3.203636  2.817143
           Other   3.092857  3.304000

In [ ]:
pt= pd.pivot_table(df,values='Student_ID', index='City', columns='Department', aggfunc='count') #on the basis of the departmnt and city no of student
pt

Department  BBA  CS  EE  Math  Physics
City
Faisalabad   40  38  38    40       34
Islamabad    43  34  33    53       34
Karachi      40  42  37    46       43
Lahore       44  42  43    48       65
Multan       40  42  27    48       36

In [ ]:
pt = pd.pivot_table(df, values='CGPA', index='Department',columns='Semester',  aggfunc='mean') #avg cgpa on basic of dep and sem
pt

Semester,1,2,3,4,5,6,7,8
Department,,,,,,,,
BBA,2.932000,2.874211,3.131562,2.995217,2.933793,2.987895,3.233913,3.161786
CS,3.179615,3.050800,3.093529,3.328276,2.920357,3.016400,2.984286,2.943158
EE,3.035909,2.776667,3.176000,3.029200,3.106250,3.271875,2.977727,2.965185
Math,3.172813,2.971250,2.963636,3.131935,2.926957,3.013077,3.140741,3.011786
Physics,3.018571,3.032333,2.984857,2.971739,2.909545,3.098065,3.087200,3.104000